---
# tasks file for Phill93.traefik
  - name: Install required tools
    become: true
    package:
      name: "{{ traefik_tools }}"
      state: present

  - name: Create traefik configuration directory
    become: true
    file:
      path: /etc/traefik
      state: directory
      owner: root
      group: root
      mode: 0750

  - name: Generate static traefik configuration
    become: true
    template:
      src: templates/traefik.json.j2
      dest: /etc/traefik/traefik.json
      owner: root
      group: root
      mode: 0640
      validate: /usr/bin/jsonlint-php %s
    register: "traefik_cmd_static_conf"

  - name: Generate dynamic traefik configuration
    become: true
    template:
      src: templates/dynamic.json.j2
      dest: /etc/traefik/dynamic.json
      owner: root
      group: root
      mode: 0640
      validate: /usr/bin/jsonlint-php %s
    register: "traefik_cmd_dyn_conf"

  - name: Create traefik network
    become: true
    docker_network:
      name: "{{ traefik_network }}"

  - name: Create traefik container
    become: true
    docker_container:
      name: traefik
      image: traefik
      restart_policy: "{{ traefik_restart_policy }}"
      restart: "{{ True if (traefik_cmd_static_conf.changed or traefik_cmd_dyn_conf.changed) else False }}"
      ports: "{{ traefik_ports }}"
      volumes: "{{ traefik_volumes + (['/var/run/docker.sock:/var/run/docker.sock'] if traefik_docker_sock else []) }}"
      networks:
        - name: "{{ traefik_network }}"