---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: debian
    box: debian/buster64
    provision: True
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  options:
    sudo: true
  lint:
    name: flake8
